os:
  - osx
language: generic
osx_image: xcode9

env:
  - PLATFORM=Mac
  - PLATFORM=iOS NAME='iPhone 6s'
  - PLATFORM=tvOS NAME='Apple TV 1080p'
  - PLATFORM=watchOS
  - PLATFORM=SPM

before_install:
  - if [ -n "$NAME" ]; then
      export UUID=$(instruments -s | ruby -e "ARGF.each_line{ |ln| ln =~ /$NAME .* \[(.*)\]/; if \$1; puts(\$1); exit; end }");
    fi

script:
  - set -o pipefail;
    case $PLATFORM in
    Mac)
      xcodebuild -scheme JSONUtilities -enableCodeCoverage YES test | xcpretty;;
    iOS|tvOS)
      open -a "simulator" --args -CurrentDeviceUDID "$UUID" && xcodebuild -scheme JSONUtilities -destination "id=$UUID" -enableCodeCoverage YES test | xcpretty;;
    watchOS)
      xcodebuild -scheme JSONUtilities -destination "name=Apple Watch - 38mm" | xcpretty;;
    SPM)
      swift build && swift test;;
    esac

after_success:
  - sleep 5
  - bash <(curl -s https://codecov.io/bash)
